// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MunDev.Data;

#nullable disable

namespace MunDev.Migrations
{
    [DbContext(typeof(MunDevContext))]
    [Migration("20250622201400_AddInvitationAndEquipoUsuario")]
    partial class AddInvitationAndEquipoUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MunDev.Models.ActividadUsuario", b =>
                {
                    b.Property<int>("ActividadUsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActividadUsuarioId"));

                    b.Property<string>("DescripcionActividad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaActividad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TipoActividad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ActividadUsuarioId")
                        .HasName("PK__Activida__9FDCB5056E041739");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ActividadUsuario", (string)null);
                });

            modelBuilder.Entity("MunDev.Models.Comentario", b =>
                {
                    b.Property<int>("ComentarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComentarioId"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("TareaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ComentarioId")
                        .HasName("PK__Comentar__F1844938DDF6317D");

                    b.HasIndex("TareaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Comentario", (string)null);
                });

            modelBuilder.Entity("MunDev.Models.Equipo", b =>
                {
                    b.Property<int>("EquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipoId"));

                    b.Property<int?>("CreadoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NombreEquipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EquipoId")
                        .HasName("PK__Equipo__DE8A0BDF3B7E5681");

                    b.HasIndex("CreadoPorUsuarioId");

                    b.ToTable("Equipo", (string)null);
                });

            modelBuilder.Entity("MunDev.Models.EquipoUsuario", b =>
                {
                    b.Property<int>("EquipoUsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipoUsuarioId"));

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaUnion")
                        .HasColumnType("datetime2");

                    b.Property<string>("RolEnEquipo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("EquipoUsuarioId");

                    b.HasIndex("EquipoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("EquipoUsuarios");
                });

            modelBuilder.Entity("MunDev.Models.Invitation", b =>
                {
                    b.Property<int>("InvitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvitationId"));

                    b.Property<int?>("AcceptedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateSent")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvitationToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("InvitedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("InvitedEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("bit");

                    b.HasKey("InvitationId");

                    b.HasIndex("AcceptedByUserId");

                    b.HasIndex("EquipoId");

                    b.HasIndex("InvitedByUserId");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("MunDev.Models.Notificacion", b =>
                {
                    b.Property<int>("NotificacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificacionId"));

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("Leida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("leida");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TipoNotificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("NotificacionId")
                        .HasName("PK__Notifica__BCC12024F14C67AA");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificacion", (string)null);
                });

            modelBuilder.Entity("MunDev.Models.Proyecto", b =>
                {
                    b.Property<int>("ProyectoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProyectoId"));

                    b.Property<int?>("CreadoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EquipoId")
                        .HasColumnType("int");

                    b.Property<string>("EstadoProyecto")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Activo");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("FechaFinEstimada")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("NombreProyecto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ProyectoId")
                        .HasName("PK__Proyecto__CF241D65D3184D83");

                    b.HasIndex("CreadoPorUsuarioId");

                    b.HasIndex("EquipoId");

                    b.ToTable("Proyecto", (string)null);
                });

            modelBuilder.Entity("MunDev.Models.ProyectoUsuario", b =>
                {
                    b.Property<int>("ProyectoUsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProyectoUsuarioId"));

                    b.Property<DateTime?>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.Property<string>("RolEnProyecto")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ProyectoUsuarioId")
                        .HasName("PK__Proyecto__ADE3541B8CC1E85B");

                    b.HasIndex("UsuarioId");

                    b.HasIndex(new[] { "ProyectoId", "UsuarioId" }, "UQ__Proyecto__5D97C31F62BAF76E")
                        .IsUnique();

                    b.ToTable("ProyectoUsuario", (string)null);
                });

            modelBuilder.Entity("MunDev.Models.Repositorio", b =>
                {
                    b.Property<int>("RepositorioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RepositorioId"));

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NombreRepositorio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.Property<string>("RepositorioUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("RepositorioURL");

                    b.HasKey("RepositorioId")
                        .HasName("PK__Reposito__7C1D3FA2AA44FB1D");

                    b.HasIndex("ProyectoId");

                    b.ToTable("Repositorio", (string)null);
                });

            modelBuilder.Entity("MunDev.Models.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RolId")
                        .HasName("PK__Rol__F92302F1E4F132AE");

                    b.HasIndex(new[] { "NombreRol" }, "UQ__Rol__4F0B537F513BCD0E")
                        .IsUnique();

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("MunDev.Models.Tarea", b =>
                {
                    b.Property<int>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TareaId"));

                    b.Property<int?>("AsignadoAusuarioId")
                        .HasColumnType("int")
                        .HasColumnName("AsignadoAUsuarioId");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoTarea")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateOnly?>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<string>("Prioridad")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Media");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TareaId")
                        .HasName("PK__Tarea__5CD8399179719ACE");

                    b.HasIndex("AsignadoAusuarioId");

                    b.HasIndex("ProyectoId");

                    b.ToTable("Tarea", (string)null);
                });

            modelBuilder.Entity("MunDev.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ContrasenaHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UsuarioId")
                        .HasName("PK__Usuario__2B3DE7B84410861C");

                    b.HasIndex(new[] { "NombreUsuario" }, "UQ__Usuario__6B0F5AE0F08876B1")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Usuario__A9D10534FFE4A6E4")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("MunDev.Models.ActividadUsuario", b =>
                {
                    b.HasOne("MunDev.Models.Usuario", "Usuario")
                        .WithMany("ActividadUsuarios")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__Actividad__Usuar__619B8048");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MunDev.Models.Comentario", b =>
                {
                    b.HasOne("MunDev.Models.Tarea", "Tarea")
                        .WithMany("Comentarios")
                        .HasForeignKey("TareaId")
                        .IsRequired()
                        .HasConstraintName("FK__Comentari__Tarea__5441852A");

                    b.HasOne("MunDev.Models.Usuario", "Usuario")
                        .WithMany("Comentarios")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__Comentari__Usuar__5535A963");

                    b.Navigation("Tarea");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MunDev.Models.Equipo", b =>
                {
                    b.HasOne("MunDev.Models.Usuario", "CreadoPorUsuario")
                        .WithMany("Equipos")
                        .HasForeignKey("CreadoPorUsuarioId")
                        .HasConstraintName("FK__Equipo__CreadoPo__3F466844");

                    b.Navigation("CreadoPorUsuario");
                });

            modelBuilder.Entity("MunDev.Models.EquipoUsuario", b =>
                {
                    b.HasOne("MunDev.Models.Equipo", "Equipo")
                        .WithMany("EquipoUsuarios")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MunDev.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MunDev.Models.Invitation", b =>
                {
                    b.HasOne("MunDev.Models.Usuario", "AcceptedByUser")
                        .WithMany()
                        .HasForeignKey("AcceptedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MunDev.Models.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MunDev.Models.Usuario", "InvitedByUser")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcceptedByUser");

                    b.Navigation("Equipo");

                    b.Navigation("InvitedByUser");
                });

            modelBuilder.Entity("MunDev.Models.Notificacion", b =>
                {
                    b.HasOne("MunDev.Models.Usuario", "Usuario")
                        .WithMany("Notificacions")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__Notificac__Usuar__5DCAEF64");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MunDev.Models.Proyecto", b =>
                {
                    b.HasOne("MunDev.Models.Usuario", "CreadoPorUsuario")
                        .WithMany("Proyectos")
                        .HasForeignKey("CreadoPorUsuarioId")
                        .HasConstraintName("FK__Proyecto__Creado__440B1D61");

                    b.HasOne("MunDev.Models.Equipo", "Equipo")
                        .WithMany("Proyectos")
                        .HasForeignKey("EquipoId")
                        .HasConstraintName("FK__Proyecto__Equipo__44FF419A");

                    b.Navigation("CreadoPorUsuario");

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("MunDev.Models.ProyectoUsuario", b =>
                {
                    b.HasOne("MunDev.Models.Proyecto", "Proyecto")
                        .WithMany("ProyectoUsuarios")
                        .HasForeignKey("ProyectoId")
                        .IsRequired()
                        .HasConstraintName("FK__ProyectoU__Proye__49C3F6B7");

                    b.HasOne("MunDev.Models.Usuario", "Usuario")
                        .WithMany("ProyectoUsuarios")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__ProyectoU__Usuar__4AB81AF0");

                    b.Navigation("Proyecto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MunDev.Models.Repositorio", b =>
                {
                    b.HasOne("MunDev.Models.Proyecto", "Proyecto")
                        .WithMany("Repositorios")
                        .HasForeignKey("ProyectoId")
                        .IsRequired()
                        .HasConstraintName("FK__Repositor__Proye__59063A47");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("MunDev.Models.Tarea", b =>
                {
                    b.HasOne("MunDev.Models.Usuario", "AsignadoAusuario")
                        .WithMany("Tareas")
                        .HasForeignKey("AsignadoAusuarioId")
                        .HasConstraintName("FK__Tarea__AsignadoA__5070F446");

                    b.HasOne("MunDev.Models.Proyecto", "Proyecto")
                        .WithMany("Tareas")
                        .HasForeignKey("ProyectoId")
                        .IsRequired()
                        .HasConstraintName("FK__Tarea__ProyectoI__4F7CD00D");

                    b.Navigation("AsignadoAusuario");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("MunDev.Models.Equipo", b =>
                {
                    b.Navigation("EquipoUsuarios");

                    b.Navigation("Proyectos");
                });

            modelBuilder.Entity("MunDev.Models.Proyecto", b =>
                {
                    b.Navigation("ProyectoUsuarios");

                    b.Navigation("Repositorios");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("MunDev.Models.Tarea", b =>
                {
                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("MunDev.Models.Usuario", b =>
                {
                    b.Navigation("ActividadUsuarios");

                    b.Navigation("Comentarios");

                    b.Navigation("Equipos");

                    b.Navigation("Notificacions");

                    b.Navigation("ProyectoUsuarios");

                    b.Navigation("Proyectos");

                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
